---
title: "Network Members"
css: styles.css
email-obfuscation: javascript
---

Black Earth Restoration Collective welcomes any restoration ecologists who identify as BIPOC or allies. If you would like to join the Black Earth Restoration Collective, please complete the following survey and we will be in contact with you shortly.

We acknowledge that not all information is meant to be shared with everyone and as such, are mindful of protecting the knowledge and personal information of our collective members. If you are a member of the Black Earth Restoration Collective and would like to be featured on our members page or update your currently featured information, please email the following with the subject line "Information for Members Page: (Your Name)" to blackearthrestoration \[at\] gmail \[dot\] com:

-   Name & Pronouns

-   Title & Affiliation(s)

-   Email or other preferred method of contact, link to personal website/social media, etc.

-   Headshot

If you have any questions or would like to get in touch with the Black Earth Restoration Collective, please feel free to email us at blackearthrestoration \[at\] gmail \[dot\] com.
